[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py

# Configuración de Logs en Consola (Live Logging)
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)-8s | %(name)-12s | %(message)s
log_cli_date_format = %H:%M:%S

# Opciones de ejecución
addopts =
    -ra
    -v
    -s
    --tb=short
    --capture=no
    -p no:cacheprovider
    --html=reports/report.html
    --self-contained-html